### ISSUE TITLE
How do i see latest version off this app in My Adobe Launch Instance

### ISSUE THREAD

**Issue by frambert** [AdobeDocs/launch.en#27] opened 2020-05-12 14:50 UTC
Hi,

I believe latest version of this app handles events and evars in product string, hhowever i don't see this version in Adobe Launch, i only see v1.0. 
i tried emailing crupe@adobe.com per the documentation: https://exchange.adobe.com/experiencecloud.details.100683.html
But haven't got response yet. 
please advise. 
Much appreciated. 
Fred

**Comment by thebenrob** [comment] 2020-09-25 13:43
@frambert, can you let us know if you are still having this issue?

**Comment by frambert** [comment] 2020-09-25 14:07
Hi Ben,

Thanks for the follow up. Seems like it.
I still see v1.0.1
[Graphical user interface, text, application  Description automatically generated]

Don’t have the option to update.

Thanks

Frédérique Rambert
Lead Analytics implementation specialist, EMEA
acceleration
A WUNDERMAN THOMPSON COMPANY
 www.acceleration.biz<https://www.acceleration.biz>

3rd Floor, Greater London House
Hampstead Road
London NW1 7QP
C
T

+33 612 181 740
+44 208 132 7815
Twitter<https://twitter.com/accelerationbiz>
LinkedIn<http://www.linkedin.com/company/acceleration>
Our blog<https://www.acceleration.biz/our-thinking/>

**Comment by thebenrob** [comment] 2020-09-25 16:03
Closing this one as a duplicate of #28

**Closed by thebenrob** 2020-09-25 16:03 UTC
Labels: question
